"""Initial migration: Create Business and LandingPage tables

Revision ID: 3215b784e4be
Revises: 
Create Date: 2025-12-23 17:40:19.639338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3215b784e4be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=200), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('unique_value_proposition', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('subheadline', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('testimonials', sa.Text(), nullable=True),
    sa.Column('about_section', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=60), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=100), nullable=True),
    sa.Column('og_description', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('html_path', sa.String(length=255), nullable=True),
    sa.Column('css_path', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_business_id'), 'landing_pages', ['business_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_business_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
